### ISSUE TITLE
Add escaped encode / decode function

### ISSUE THREAD

**Issue by robamu** [Lx/python-dlestxetx#1]
Hello,

I wanted to ask if you are interested in an escaped version of the DLE encoding.
The existing package would be easily extensible by adding two new functions:

- ` encode_escaped` 
-  `decode_escaped`

The escaped versions can be found here: https://github.com/robamu-org/py-dle-encoder/blob/main/dle_encoder.py

Basically, STX and ETX occurences are escaped as well by replacing them with DLE + Escaped Byte. That way, STX and ETX will not occur anymore and the receiving side implementation can simply search for the STX and ETX markers to start encoding/decoding. There is a corresponding OpenSource implementation for C++ as well, which might be useful for everyone which wants to decode the packets generate with the functions above on something like a MCU (and that is what we're doing as well)

If you are interesting, I can create a PR with tests and documentation. Then, there would be no need for two packages doing very similar things

**Comment by Lx** [comment]
Hi Robin.  Thank you for taking the time to get in touch about extending the `dlestxetx` Python module.  I'm very sorry for taking this long to respond (I guess we could joke that I'm still responding in the "same month"!).

I see that you did eventually release [`dle-encoder` on PyPI](https://pypi.org/project/dle-encoder), but I do appreciate your consideration for the PyPI ecosystem by considering whether the two functionalities could exist within one package.

I'm open to the changes, but equally, I'm also fine with the two different tasks being satisfied by two different packages (especially since they've both now been published).

Are you still interested in merging the two?

**Comment by robamu** [comment]
I think its okay to have two different encoders. I think we might move to something more predictable like COBS ( https://en.wikipedia.org/wiki/Consistent_Overhead_Byte_Stuffing ) for our purposes of having a transport layer anyway.

**Comment by Lx** [comment]
Thanks Robin.  I agree with you, so I think we should close this issue for now.  If you change your mind in future, I'm happy to cooperate.  Thank you again for getting in touch.
